before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: afosto
    name: cli
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

brews:
  - name: afosto-cli
    tap:
      owner: afosto
      name: homebrew-tap

    commit_author:
      name: goreleaserbot
      email: dev@afosto.com

    folder: Formula

    homepage: "https://afosto.com/"
    description: "CLI tool for interaction with Afosto/IO"
    license: "Apache-2.0"