before:
  hooks:
    - go mod download

builds:
  - id: afosto
    main: ./cmd/afosto/afosto.go
    binary: afosto
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: afosto
    name: cli
  name_template: "afosto-{{.ProjectName}}-v{{.Version}}"

brews:
  - name: afosto
    tap:
      owner: afosto
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_author:
      name: goreleaserbot
      email: dev@afosto.com

    folder: Formula

    homepage: "https://afosto.com/"
    description: "CLI tool for interaction with Afosto/IO"
    license: "Apache-2.0"
    test: |
      afosto version
    install: |
      bin.install "afosto"
    caveats: "Thanks for installing the Afosto CLI! If you have any feedback, please open up an issue at github.com/afosto/cli. Run `afosto login` to authenticate with the API."